# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_bram_0/test_phasegen_1_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'test_phasegen_1_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_bram_0/test_phasegen_1_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_phasegen_1_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_bram_0/test_phasegen_1_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'test_phasegen_1_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_bram_0/test_phasegen_1_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_phasegen_1_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
