# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: constraint_1.xdc

# Block Designs: bd/nco_1/nco_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1 || ORIG_REF_NAME==nco_1}]

# IP: bd/nco_1/ip/nco_1_processing_system7_0_0/nco_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_processing_system7_0_0 || ORIG_REF_NAME==nco_1_processing_system7_0_0}]

# IP: bd/nco_1/ip/nco_1_axi_bram_ctrl_0_0/nco_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==nco_1_axi_bram_ctrl_0_0}]

# IP: bd/nco_1/ip/nco_1_axi_bram_ctrl_0_bram_0/nco_1_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==nco_1_axi_bram_ctrl_0_bram_0}]

# IP: bd/nco_1/ip/nco_1_axi_smc_0/nco_1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_axi_smc_0 || ORIG_REF_NAME==nco_1_axi_smc_0}]

# IP: bd/nco_1/ip/nco_1_rst_ps7_0_100M_0/nco_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==nco_1_rst_ps7_0_100M_0}]

# IP: bd/nco_1/ip/nco_1_axi_bram_ctrl_1_0/nco_1_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==nco_1_axi_bram_ctrl_1_0}]

# IP: bd/nco_1/ip/nco_1_axi_bram_ctrl_1_bram_0/nco_1_axi_bram_ctrl_1_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==nco_1_axi_bram_ctrl_1_bram_0}]

# IP: bd/nco_1/ip/nco_1_axi_bram_ctrl_2_0/nco_1_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_axi_bram_ctrl_2_0 || ORIG_REF_NAME==nco_1_axi_bram_ctrl_2_0}]

# IP: bd/nco_1/ip/nco_1_axi_bram_ctrl_2_bram_0/nco_1_axi_bram_ctrl_2_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_axi_bram_ctrl_2_bram_0 || ORIG_REF_NAME==nco_1_axi_bram_ctrl_2_bram_0}]

# IP: bd/nco_1/ip/nco_1_jtag_axi_0_0/nco_1_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_jtag_axi_0_0 || ORIG_REF_NAME==nco_1_jtag_axi_0_0}]

# IP: bd/nco_1/ip/nco_1_phasegen_0_0/nco_1_phasegen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_phasegen_0_0 || ORIG_REF_NAME==nco_1_phasegen_0_0}]

# IP: bd/nco_1/ip/nco_1_nco_0_0/nco_1_nco_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_nco_0_0 || ORIG_REF_NAME==nco_1_nco_0_0}]

# IP: bd/nco_1/ip/nco_1_datadevnull_0_0/nco_1_datadevnull_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nco_1_datadevnull_0_0 || ORIG_REF_NAME==nco_1_datadevnull_0_0}]

# XDC: bd/nco_1/nco_1_ooc.xdc
