# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.cache/wt [current_project]
set_property parent.project_path Z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths z:/Documents/workspace/zysh101/iplib [current_project]
set_property ip_output_repo z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/hdl/nco_1_wrapper.v
add_files Z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/nco_1.bd
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_processing_system7_0_0/nco_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_bram_ctrl_0_0/nco_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_bram_ctrl_0_bram_0/nco_1_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_10/bd_9d82_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_19/bd_9d82_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_25/bd_9d82_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_32/bd_9d82_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_39/bd_9d82_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_40/bd_9d82_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_41/bd_9d82_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_42/bd_9d82_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_43/bd_9d82_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_44/bd_9d82_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_33/bd_9d82_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_34/bd_9d82_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_35/bd_9d82_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_36/bd_9d82_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_37/bd_9d82_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_26/bd_9d82_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_27/bd_9d82_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_28/bd_9d82_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_29/bd_9d82_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_30/bd_9d82_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_20/bd_9d82_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_21/bd_9d82_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_22/bd_9d82_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_23/bd_9d82_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_24/bd_9d82_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_11/bd_9d82_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_12/bd_9d82_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_13/bd_9d82_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_14/bd_9d82_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_15/bd_9d82_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_2/bd_9d82_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_3/bd_9d82_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_4/bd_9d82_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_5/bd_9d82_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_6/bd_9d82_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_1/bd_9d82_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/bd_0/ip/ip_1/bd_9d82_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_rst_ps7_0_100M_0/nco_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_rst_ps7_0_100M_0/nco_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_rst_ps7_0_100M_0/nco_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_bram_ctrl_1_0/nco_1_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_bram_ctrl_1_bram_0/nco_1_axi_bram_ctrl_1_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_bram_ctrl_2_0/nco_1_axi_bram_ctrl_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_axi_bram_ctrl_2_bram_0/nco_1_axi_bram_ctrl_2_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/constraints/nco_1_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/constraints/nco_1_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/nco_1_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_phasegen_0_0/constraints/phasegen_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_nco_0_0/constraints/nco_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_datadevnull_0_0/constraints/datadevnull_ooc.xdc]
set_property used_in_implementation false [get_files -all Z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/nco_1_ooc.xdc]
set_property is_locked true [get_files Z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/nco_1.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/constrs_1/constraint_1.xdc
set_property used_in_implementation false [get_files z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/constrs_1/constraint_1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top nco_1_wrapper -part xc7z010clg225-1


write_checkpoint -force -noxdef nco_1_wrapper.dcp

catch { report_utilization -file nco_1_wrapper_utilization_synth.rpt -pb nco_1_wrapper_utilization_synth.pb }
