# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: constraint_1.xdc

# Block Designs: bd/test_phasegen_1/test_phasegen_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1 || ORIG_REF_NAME==test_phasegen_1}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_processing_system7_0_0/test_phasegen_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_processing_system7_0_0 || ORIG_REF_NAME==test_phasegen_1_processing_system7_0_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_0/test_phasegen_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==test_phasegen_1_axi_bram_ctrl_0_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_bram_0/test_phasegen_1_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==test_phasegen_1_axi_bram_ctrl_0_bram_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/test_phasegen_1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_axi_smc_0 || ORIG_REF_NAME==test_phasegen_1_axi_smc_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_rst_ps7_0_100M_0/test_phasegen_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==test_phasegen_1_rst_ps7_0_100M_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_1_0/test_phasegen_1_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==test_phasegen_1_axi_bram_ctrl_1_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_1_bram_0/test_phasegen_1_axi_bram_ctrl_1_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==test_phasegen_1_axi_bram_ctrl_1_bram_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_jtag_axi_0_0/test_phasegen_1_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_jtag_axi_0_0 || ORIG_REF_NAME==test_phasegen_1_jtag_axi_0_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_phasegen_0_0/test_phasegen_1_phasegen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_phasegen_0_0 || ORIG_REF_NAME==test_phasegen_1_phasegen_0_0}]

# IP: bd/test_phasegen_1/ip/test_phasegen_1_phasedevnull_0_0/test_phasegen_1_phasedevnull_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_phasegen_1_phasedevnull_0_0 || ORIG_REF_NAME==test_phasegen_1_phasedevnull_0_0}]

# XDC: bd/test_phasegen_1/test_phasegen_1_ooc.xdc
