# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.cache/wt [current_project]
set_property parent.project_path Z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths z:/Documents/workspace/zysh101/iplib [current_project]
set_property ip_output_repo z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/hdl/test_phasegen_1_wrapper.v
add_files Z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/test_phasegen_1.bd
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_processing_system7_0_0/test_phasegen_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_0/test_phasegen_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_0_bram_0/test_phasegen_1_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_10/bd_b6d7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_19/bd_b6d7_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_25/bd_b6d7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_32/bd_b6d7_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_33/bd_b6d7_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_34/bd_b6d7_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_35/bd_b6d7_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_36/bd_b6d7_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_37/bd_b6d7_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_26/bd_b6d7_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_27/bd_b6d7_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_28/bd_b6d7_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_29/bd_b6d7_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_30/bd_b6d7_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_20/bd_b6d7_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_21/bd_b6d7_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_22/bd_b6d7_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_23/bd_b6d7_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_24/bd_b6d7_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_11/bd_b6d7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_12/bd_b6d7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_13/bd_b6d7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_14/bd_b6d7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_15/bd_b6d7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_2/bd_b6d7_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_3/bd_b6d7_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_4/bd_b6d7_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_5/bd_b6d7_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_6/bd_b6d7_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_1/bd_b6d7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/bd_0/ip/ip_1/bd_b6d7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_rst_ps7_0_100M_0/test_phasegen_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_rst_ps7_0_100M_0/test_phasegen_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_rst_ps7_0_100M_0/test_phasegen_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_1_0/test_phasegen_1_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_axi_bram_ctrl_1_bram_0/test_phasegen_1_axi_bram_ctrl_1_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_jtag_axi_0_0/constraints/test_phasegen_1_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_jtag_axi_0_0/constraints/test_phasegen_1_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_jtag_axi_0_0/test_phasegen_1_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_phasegen_0_0/constraints/phasegen_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/ip/test_phasegen_1_phasedevnull_0_0/constraints/phasedevnull_ooc.xdc]
set_property used_in_implementation false [get_files -all Z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/test_phasegen_1_ooc.xdc]
set_property is_locked true [get_files Z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/sources_1/bd/test_phasegen_1/test_phasegen_1.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/constrs_1/constraint_1.xdc
set_property used_in_implementation false [get_files z:/Documents/workspace/zysh101/src/tcl/testphasegen/test_phasegen/test_phasegen.srcs/constrs_1/constraint_1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top test_phasegen_1_wrapper -part xc7z010clg225-1


write_checkpoint -force -noxdef test_phasegen_1_wrapper.dcp

catch { report_utilization -file test_phasegen_1_wrapper_utilization_synth.rpt -pb test_phasegen_1_wrapper_utilization_synth.pb }
