set_property SRC_FILE_INFO {cfile:z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/constrs_1/constraint_1.xdc rfile:../../../nco.srcs/constrs_1/constraint_1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[16]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[4]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets nco_1_i/phasegen_0/outval_V_TVALID]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[20]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[0]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[22]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[13]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[24]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[28]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[2]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[12]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[7]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[19]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[11]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[15]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[17]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[18]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[14]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[1]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets nco_1_i/phasegen_0/outval_V_TREADY]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[3]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[5]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[6]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[8]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[27]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[29]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[31]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[30]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[21]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[23]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[25]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[26]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[9]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/phasegen_0/outval_V_TDATA[10]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[15]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[9]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[23]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[31]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[19]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[3]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[2]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[5]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[20]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[7]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[29]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[17]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[11]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets nco_1_i/nco_0/dataout_V_TREADY]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[14]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[26]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[8]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[16]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[4]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[13]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[12]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[10]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[6]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[0]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets nco_1_i/nco_0/dataout_V_TVALID]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[1]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[28]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[30]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[27]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[18]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[22]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[24]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[25]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {nco_1_i/nco_0/dataout_V_TDATA[21]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list nco_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {nco_1_i/phasegen_0/outval_V_TDATA[0]} {nco_1_i/phasegen_0/outval_V_TDATA[1]} {nco_1_i/phasegen_0/outval_V_TDATA[2]} {nco_1_i/phasegen_0/outval_V_TDATA[3]} {nco_1_i/phasegen_0/outval_V_TDATA[4]} {nco_1_i/phasegen_0/outval_V_TDATA[5]} {nco_1_i/phasegen_0/outval_V_TDATA[6]} {nco_1_i/phasegen_0/outval_V_TDATA[7]} {nco_1_i/phasegen_0/outval_V_TDATA[8]} {nco_1_i/phasegen_0/outval_V_TDATA[9]} {nco_1_i/phasegen_0/outval_V_TDATA[10]} {nco_1_i/phasegen_0/outval_V_TDATA[11]} {nco_1_i/phasegen_0/outval_V_TDATA[12]} {nco_1_i/phasegen_0/outval_V_TDATA[13]} {nco_1_i/phasegen_0/outval_V_TDATA[14]} {nco_1_i/phasegen_0/outval_V_TDATA[15]} {nco_1_i/phasegen_0/outval_V_TDATA[16]} {nco_1_i/phasegen_0/outval_V_TDATA[17]} {nco_1_i/phasegen_0/outval_V_TDATA[18]} {nco_1_i/phasegen_0/outval_V_TDATA[19]} {nco_1_i/phasegen_0/outval_V_TDATA[20]} {nco_1_i/phasegen_0/outval_V_TDATA[21]} {nco_1_i/phasegen_0/outval_V_TDATA[22]} {nco_1_i/phasegen_0/outval_V_TDATA[23]} {nco_1_i/phasegen_0/outval_V_TDATA[24]} {nco_1_i/phasegen_0/outval_V_TDATA[25]} {nco_1_i/phasegen_0/outval_V_TDATA[26]} {nco_1_i/phasegen_0/outval_V_TDATA[27]} {nco_1_i/phasegen_0/outval_V_TDATA[28]} {nco_1_i/phasegen_0/outval_V_TDATA[29]} {nco_1_i/phasegen_0/outval_V_TDATA[30]} {nco_1_i/phasegen_0/outval_V_TDATA[31]}]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {nco_1_i/nco_0/dataout_V_TDATA[0]} {nco_1_i/nco_0/dataout_V_TDATA[1]} {nco_1_i/nco_0/dataout_V_TDATA[2]} {nco_1_i/nco_0/dataout_V_TDATA[3]} {nco_1_i/nco_0/dataout_V_TDATA[4]} {nco_1_i/nco_0/dataout_V_TDATA[5]} {nco_1_i/nco_0/dataout_V_TDATA[6]} {nco_1_i/nco_0/dataout_V_TDATA[7]} {nco_1_i/nco_0/dataout_V_TDATA[8]} {nco_1_i/nco_0/dataout_V_TDATA[9]} {nco_1_i/nco_0/dataout_V_TDATA[10]} {nco_1_i/nco_0/dataout_V_TDATA[11]} {nco_1_i/nco_0/dataout_V_TDATA[12]} {nco_1_i/nco_0/dataout_V_TDATA[13]} {nco_1_i/nco_0/dataout_V_TDATA[14]} {nco_1_i/nco_0/dataout_V_TDATA[15]} {nco_1_i/nco_0/dataout_V_TDATA[16]} {nco_1_i/nco_0/dataout_V_TDATA[17]} {nco_1_i/nco_0/dataout_V_TDATA[18]} {nco_1_i/nco_0/dataout_V_TDATA[19]} {nco_1_i/nco_0/dataout_V_TDATA[20]} {nco_1_i/nco_0/dataout_V_TDATA[21]} {nco_1_i/nco_0/dataout_V_TDATA[22]} {nco_1_i/nco_0/dataout_V_TDATA[23]} {nco_1_i/nco_0/dataout_V_TDATA[24]} {nco_1_i/nco_0/dataout_V_TDATA[25]} {nco_1_i/nco_0/dataout_V_TDATA[26]} {nco_1_i/nco_0/dataout_V_TDATA[27]} {nco_1_i/nco_0/dataout_V_TDATA[28]} {nco_1_i/nco_0/dataout_V_TDATA[29]} {nco_1_i/nco_0/dataout_V_TDATA[30]} {nco_1_i/nco_0/dataout_V_TDATA[31]}]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list nco_1_i/nco_0/dataout_V_TREADY]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list nco_1_i/nco_0/dataout_V_TVALID]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list nco_1_i/phasegen_0/outval_V_TREADY]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list nco_1_i/phasegen_0/outval_V_TVALID]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
