// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _devnull_HH_
#define _devnull_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct devnull : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > params_V_Addr_A;
    sc_out< sc_logic > params_V_EN_A;
    sc_out< sc_lv<4> > params_V_WEN_A;
    sc_out< sc_lv<32> > params_V_Din_A;
    sc_in< sc_lv<32> > params_V_Dout_A;


    // Module declarations
    devnull(sc_module_name name);
    SC_HAS_PROCESS(devnull);

    ~devnull();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > max_V_reg_70;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > counter_V_fu_59_p2;
    sc_signal< sc_lv<32> > counter_V_reg_83;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > t_V_reg_43;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > params_V_Addr_A_orig;
    sc_signal< sc_lv<1> > exitcond_fu_54_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_counter_V_fu_59_p2();
    void thread_exitcond_fu_54_p2();
    void thread_params_V_Addr_A();
    void thread_params_V_Addr_A_orig();
    void thread_params_V_Din_A();
    void thread_params_V_EN_A();
    void thread_params_V_WEN_A();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
