# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/nco_1_jtag_axi_0_0.xci
# IP: The module: 'nco_1_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'nco_1_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/nco_1_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nco_1_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/nco_1_jtag_axi_0_0.xci
# IP: The module: 'nco_1_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'nco_1_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: z:/Documents/workspace/zysh101/src/tcl/testnco/nco/nco.srcs/sources_1/bd/nco_1/ip/nco_1_jtag_axi_0_0/nco_1_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nco_1_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
