-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dynamics is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    inv_V_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    inv_V_TVALID : IN STD_LOGIC;
    inv_V_TREADY : OUT STD_LOGIC;
    outv_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    outv_V_TVALID : OUT STD_LOGIC;
    outv_V_TREADY : IN STD_LOGIC;
    params_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    params_V_EN_A : OUT STD_LOGIC;
    params_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    params_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    params_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    params_V_Clk_A : OUT STD_LOGIC;
    params_V_Rst_A : OUT STD_LOGIC );
end;


architecture behav of dynamics is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dynamics,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z010clg225-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.254000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=218,HLS_SYN_LUT=164}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal inv_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal inv_V_0_vld_in : STD_LOGIC;
    signal inv_V_0_vld_out : STD_LOGIC;
    signal inv_V_0_ack_in : STD_LOGIC;
    signal inv_V_0_ack_out : STD_LOGIC;
    signal inv_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal inv_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal inv_V_0_sel_rd : STD_LOGIC := '0';
    signal inv_V_0_sel_wr : STD_LOGIC := '0';
    signal inv_V_0_sel : STD_LOGIC;
    signal inv_V_0_load_A : STD_LOGIC;
    signal inv_V_0_load_B : STD_LOGIC;
    signal inv_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal inv_V_0_state_cmp_full : STD_LOGIC;
    signal outv_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal outv_V_1_vld_in : STD_LOGIC;
    signal outv_V_1_vld_out : STD_LOGIC;
    signal outv_V_1_ack_in : STD_LOGIC;
    signal outv_V_1_ack_out : STD_LOGIC;
    signal outv_V_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal outv_V_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal outv_V_1_sel_rd : STD_LOGIC := '0';
    signal outv_V_1_sel_wr : STD_LOGIC := '0';
    signal outv_V_1_sel : STD_LOGIC;
    signal outv_V_1_load_A : STD_LOGIC;
    signal outv_V_1_load_B : STD_LOGIC;
    signal outv_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal outv_V_1_state_cmp_full : STD_LOGIC;
    signal inv_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal outv_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_3_fu_70_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_3_reg_95 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_reg_100 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_fu_85_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lut_fu_63_ap_done : STD_LOGIC;
    signal grp_lut_fu_63_ap_start : STD_LOGIC;
    signal grp_lut_fu_63_ap_idle : STD_LOGIC;
    signal grp_lut_fu_63_ap_ready : STD_LOGIC;
    signal grp_lut_fu_63_params_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lut_fu_63_params_V_EN_A : STD_LOGIC;
    signal grp_lut_fu_63_params_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lut_fu_63_params_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lut_fu_63_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_reg_grp_lut_fu_63_ap_start : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);

    component lut IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_V : IN STD_LOGIC_VECTOR (23 downto 0);
        params_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        params_V_EN_A : OUT STD_LOGIC;
        params_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        params_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        params_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    grp_lut_fu_63 : component lut
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_lut_fu_63_ap_start,
        ap_done => grp_lut_fu_63_ap_done,
        ap_idle => grp_lut_fu_63_ap_idle,
        ap_ready => grp_lut_fu_63_ap_ready,
        in_V => tmp_3_reg_95,
        params_V_Addr_A => grp_lut_fu_63_params_V_Addr_A,
        params_V_EN_A => grp_lut_fu_63_params_V_EN_A,
        params_V_WEN_A => grp_lut_fu_63_params_V_WEN_A,
        params_V_Din_A => grp_lut_fu_63_params_V_Din_A,
        params_V_Dout_A => params_V_Dout_A,
        ap_return => grp_lut_fu_63_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_lut_fu_63_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_grp_lut_fu_63_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (inv_V_0_vld_out = ap_const_logic_1))) then 
                    ap_reg_grp_lut_fu_63_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_lut_fu_63_ap_ready)) then 
                    ap_reg_grp_lut_fu_63_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    inv_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                inv_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = inv_V_0_ack_out) and (ap_const_logic_1 = inv_V_0_vld_out))) then 
                                        inv_V_0_sel_rd <= not(inv_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    inv_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                inv_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = inv_V_0_vld_in) and (ap_const_logic_1 = inv_V_0_ack_in))) then 
                                        inv_V_0_sel_wr <= not(inv_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    inv_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                inv_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = inv_V_0_vld_in) and (ap_const_logic_1 = inv_V_0_ack_out) and (inv_V_0_state = ap_const_lv2_3)) or ((ap_const_logic_0 = inv_V_0_vld_in) and (inv_V_0_state = ap_const_lv2_2)))) then 
                    inv_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = inv_V_0_vld_in) and (ap_const_logic_0 = inv_V_0_ack_out) and (inv_V_0_state = ap_const_lv2_3)) or ((ap_const_logic_0 = inv_V_0_ack_out) and (inv_V_0_state = ap_const_lv2_1)))) then 
                    inv_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = inv_V_0_vld_in) and (inv_V_0_state = ap_const_lv2_2)) or ((ap_const_logic_1 = inv_V_0_ack_out) and (inv_V_0_state = ap_const_lv2_1)) or ((inv_V_0_state = ap_const_lv2_3) and not(((ap_const_logic_1 = inv_V_0_vld_in) and (ap_const_logic_0 = inv_V_0_ack_out))) and not(((ap_const_logic_0 = inv_V_0_vld_in) and (ap_const_logic_1 = inv_V_0_ack_out)))))) then 
                    inv_V_0_state <= ap_const_lv2_3;
                else 
                    inv_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    outv_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                outv_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = outv_V_1_ack_out) and (ap_const_logic_1 = outv_V_1_vld_out))) then 
                                        outv_V_1_sel_rd <= not(outv_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    outv_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                outv_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = outv_V_1_vld_in) and (ap_const_logic_1 = outv_V_1_ack_in))) then 
                                        outv_V_1_sel_wr <= not(outv_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    outv_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                outv_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = outv_V_1_vld_in) and (ap_const_logic_1 = outv_V_1_ack_out) and (ap_const_lv2_3 = outv_V_1_state)) or ((ap_const_logic_0 = outv_V_1_vld_in) and (ap_const_lv2_2 = outv_V_1_state)))) then 
                    outv_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = outv_V_1_vld_in) and (ap_const_logic_0 = outv_V_1_ack_out) and (ap_const_lv2_3 = outv_V_1_state)) or ((ap_const_logic_0 = outv_V_1_ack_out) and (ap_const_lv2_1 = outv_V_1_state)))) then 
                    outv_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = outv_V_1_vld_in) and (ap_const_lv2_2 = outv_V_1_state)) or ((ap_const_logic_1 = outv_V_1_ack_out) and (ap_const_lv2_1 = outv_V_1_state)) or ((ap_const_lv2_3 = outv_V_1_state) and not(((ap_const_logic_1 = outv_V_1_vld_in) and (ap_const_logic_0 = outv_V_1_ack_out))) and not(((ap_const_logic_0 = outv_V_1_vld_in) and (ap_const_logic_1 = outv_V_1_ack_out)))))) then 
                    outv_V_1_state <= ap_const_lv2_3;
                else 
                    outv_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = inv_V_0_load_A)) then
                inv_V_0_payload_A <= inv_V_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = inv_V_0_load_B)) then
                inv_V_0_payload_B <= inv_V_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = outv_V_1_load_A)) then
                outv_V_1_payload_A <= tmp_1_fu_85_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = outv_V_1_load_B)) then
                outv_V_1_payload_B <= tmp_1_fu_85_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (inv_V_0_vld_out = ap_const_logic_1))) then
                tmp_2_reg_100 <= inv_V_0_data_out(30 downto 24);
                tmp_3_reg_95 <= tmp_3_fu_70_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (inv_V_0_vld_out, outv_V_1_ack_in, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, grp_lut_fu_63_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (inv_V_0_vld_out = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and not(((ap_const_logic_0 = outv_V_1_ack_in) or (ap_const_logic_0 = grp_lut_fu_63_ap_done))))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (outv_V_1_ack_in = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_lut_fu_63_ap_start <= ap_reg_grp_lut_fu_63_ap_start;
    inv_V_0_ack_in <= inv_V_0_state(1);

    inv_V_0_ack_out_assign_proc : process(inv_V_0_vld_out, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (inv_V_0_vld_out = ap_const_logic_1))) then 
            inv_V_0_ack_out <= ap_const_logic_1;
        else 
            inv_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    inv_V_0_data_out_assign_proc : process(inv_V_0_payload_A, inv_V_0_payload_B, inv_V_0_sel)
    begin
        if ((ap_const_logic_1 = inv_V_0_sel)) then 
            inv_V_0_data_out <= inv_V_0_payload_B;
        else 
            inv_V_0_data_out <= inv_V_0_payload_A;
        end if; 
    end process;

    inv_V_0_load_A <= (inv_V_0_state_cmp_full and not(inv_V_0_sel_wr));
    inv_V_0_load_B <= (inv_V_0_sel_wr and inv_V_0_state_cmp_full);
    inv_V_0_sel <= inv_V_0_sel_rd;
    inv_V_0_state_cmp_full <= '0' when (inv_V_0_state = ap_const_lv2_1) else '1';
    inv_V_0_vld_in <= inv_V_TVALID;
    inv_V_0_vld_out <= inv_V_0_state(0);

    inv_V_TDATA_blk_n_assign_proc : process(inv_V_0_state, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inv_V_TDATA_blk_n <= inv_V_0_state(0);
        else 
            inv_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    inv_V_TREADY <= inv_V_0_state(1);
    outv_V_1_ack_in <= outv_V_1_state(1);
    outv_V_1_ack_out <= outv_V_TREADY;

    outv_V_1_data_out_assign_proc : process(outv_V_1_payload_A, outv_V_1_payload_B, outv_V_1_sel)
    begin
        if ((ap_const_logic_1 = outv_V_1_sel)) then 
            outv_V_1_data_out <= outv_V_1_payload_B;
        else 
            outv_V_1_data_out <= outv_V_1_payload_A;
        end if; 
    end process;

    outv_V_1_load_A <= (outv_V_1_state_cmp_full and not(outv_V_1_sel_wr));
    outv_V_1_load_B <= (outv_V_1_sel_wr and outv_V_1_state_cmp_full);
    outv_V_1_sel <= outv_V_1_sel_rd;
    outv_V_1_state_cmp_full <= '0' when (outv_V_1_state = ap_const_lv2_1) else '1';

    outv_V_1_vld_in_assign_proc : process(outv_V_1_ack_in, ap_CS_fsm_state3, grp_lut_fu_63_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and not(((ap_const_logic_0 = outv_V_1_ack_in) or (ap_const_logic_0 = grp_lut_fu_63_ap_done))))) then 
            outv_V_1_vld_in <= ap_const_logic_1;
        else 
            outv_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    outv_V_1_vld_out <= outv_V_1_state(0);
    outv_V_TDATA <= outv_V_1_data_out;

    outv_V_TDATA_blk_n_assign_proc : process(outv_V_1_state, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            outv_V_TDATA_blk_n <= outv_V_1_state(1);
        else 
            outv_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outv_V_TVALID <= outv_V_1_state(0);
    params_V_Addr_A <= grp_lut_fu_63_params_V_Addr_A;
    params_V_Clk_A <= ap_clk;
    params_V_Din_A <= ap_const_lv32_0;
    params_V_EN_A <= grp_lut_fu_63_params_V_EN_A;

    params_V_Rst_A_assign_proc : process(ap_rst_n)
    begin
                params_V_Rst_A <= not(ap_rst_n);
    end process;

    params_V_WEN_A <= ap_const_lv4_0;
    tmp_1_fu_85_p4 <= ((ap_const_lv1_0 & tmp_2_reg_100) & grp_lut_fu_63_ap_return);
    tmp_3_fu_70_p1 <= inv_V_0_data_out(24 - 1 downto 0);
end behav;
